# Configuración específica para Docker
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/gymdb
    username: gymuser
    password: gympass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # Configuración para Docker networking
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000

# Server configuration
server:
  port: 8080

# Logging configuration
logging:
  level:
    com.example.gym: INFO
    org.springframework.security: DEBUG