# Configuración específica para Docker
jwt:
  secret: "YjFhMmMzZDRlNWY2ZzdoOGk5ajBrMWwybTNuNG81cDZxN3I4czl0MHUxdjJ3M3g0eTV6NmE3YjhjOWQwZTFmMmczaDRpNWo2azdsOG05bjBvMXAy"

# Resend Email Configuration
resend:
  api:
    key: "re_TPpcUdx1_3SE1iat5PUgvL3VuAxLkDfL1"

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/gymdb
    username: gymuser
    password: gympass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # Configuración para Docker networking
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration ya está configurado arriba

# Server configuration
server:
  port: 8080

# Logging configuration
logging:
  level:
    com.example.gym: INFO
    org.springframework.security: DEBUG